on:  
  push:
    tags:
      - 'v*'

env:
  DOCKER_PROJECT_DIR: .
  REGISTRY: ghcr.io
  IMAGE_NAMESPACE: andtechstudios
  IMAGE_NAME: ${{ github.repository }}

jobs:
  Deploy (GitHub):
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner  }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v1
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ${{ env.DOCKER_PROJECT_DIR }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  Deploy (Docker Hub):
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3      
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: ${{ env.IMAGE_NAMESPACE }}/${{ env.IMAGE_NAME }}
      - uses: docker/build-push-action@v2
        with:
          context: ${{ env.DOCKER_PROJECT_DIR }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}